### ISSUE TITLE
Number of the next cluster取值范围的疑问

### ISSUE THREAD

**Issue by txl1290** [cooder-org/mos#1]
@yanxiyue 
对于2G的文件系统总共有65536个cluster，不过FAT16X关于Number of the next cluster的定义是0003h - FFEFh，只能表达到65520个cluster。

这个是说后面几个cluster无法正常申请使用么，还是说有别的什么原因？

1. 如果扩大next cluster的取值范围到65536，会和FFF8h等值的定义冲突。
2. 如果不扩大，最后16个cluster无法组织连续簇的文件。next cluster取值范围表达不了。

ps：
现在我对FAT链表的理解是，前n个cluster区域是非数据区的预留，数据区新申请的都是n+1之后新的cluster，最大值是65536（offset = 65535）。

**Comment by yanxiyue** [comment]
我查过这一段的历史，不知道对不对，大意是说最后几个cluster是保留的，不让用。
